### ISSUE TITLE
Litecoin support (todo list)

### ISSUE THREAD

**Issue by doc-hex** [opendime/chrome-opendime-extension#2]
- [x] doesn't check signature correctly for Litecoin
- [x] says making _Bitcoin_ address when generating key
- [x] should highlight that it's a Litcoin Opendime (add their logo image somwhere?)

**Comment by doc-hex** [comment]
- [x] maybe: add `litecoin:` url-scheme to QR code link

**Comment by doc-hex** [comment]
- [x] needs different list of Litecoin explorers
- [x] search for other 'bitcoin' strings

**Comment by doc-hex** [comment]
Didn't mean to push this yet but Litecoin support is on master now.
